### ISSUE TITLE
Models, derived parameters and BIDS suffixes 

### ISSUE THREAD

**Issue by oesteban** [bids-standard/bids-bep016#12]
I think there is a higher-level discussion going on in the @bids-standard/derivatives core. Let's see what they have to say and then address https://github.com/bids-standard/bids-bep016/pull/5#discussion_r314205390

Shout out to @effigies, in case he can point us to other threads about this models/suffixes discussion.

**Comment by effigies** [comment]
Computational model derivatives:

* [Parameter estimates](https://docs.google.com/document/d/1oaBWmkrUqH28oQb1PTO-rG_kuwNX9KqAoE9i5iDh1xw/edit?ts=5ca50bb2#heading=h.22yjxdqsuj)
* [Internal variables](https://docs.google.com/document/d/1oaBWmkrUqH28oQb1PTO-rG_kuwNX9KqAoE9i5iDh1xw/edit?ts=5ca50bb2#heading=h.1pj6vppi9qzw)

Statistical model derivatives: Main place there was any discussion was in https://github.com/poldracklab/fitlins/issues/125

**Comment by oesteban** [comment]
Seems like the shared documents require some access permissions.

**Comment by effigies** [comment]
Made a copy and updated the links. I don't have permissions to change permissions on the original.

**Comment by arokem** [comment]
This is still, of course, relevant. However, there are more up-to-date iterations of this (e.g., under #69). Closing.
