### ISSUE TITLE
Managing NIfTI intent fields

### ISSUE THREAD

**Issue by oesteban** [bids-standard/bids-bep016#15]
Comes from https://github.com/bids-standard/bids-bep016/pull/5#discussion_r320910555

**Comment by arokem** [comment]
To clarify: there is a nii-compliant way to write out DTI-specific derivatives. But many software libraries don't implement anything to deal with this compliant way of doing things, instead just doing... whatever. 

Do we want to support the nii-compliant way of doing things? As the only way of doing things? Or one of a couple of options? This might intersect with #34 in the sense that this could be the role of some software that takes output of different processing pipelines and puts them in that format.

**Comment by Lestropie** [comment]
My personal preference would be to not interpret the NIfTI intent fields at all. BIDS metadata via JSON should completely supersede such things, as its capabilities will be a superset. Relevance moreso to #23 is that if a piece of software is known to read / write those intend fields, then any conversion to/from BIDS Derivatives should handle such appropriately.

**Comment by arokem** [comment]
Makes sense. Closing.
