### ISSUE TITLE
Clarify whether Pasternak et al should be cited with Free-water DTI model description

### ISSUE THREAD

**Issue by oesteban** [bids-standard/bids-bep016#16]
Comes from https://github.com/bids-standard/bids-bep016/pull/5#discussion_r320922984

**Comment by arokem** [comment]
I believe that the Hoy and Pasternak methods would produce the same parameters: `f` for the free water fraction + 6 tensor parameters, so I think that we can cite both Hoy and Pasternak for this.

**Comment by arokem** [comment]
Besides, it looks like fwdti is currently out of scope, so closing.

**Comment by Lestropie** [comment]
> it looks like fwdti is currently out of scope

If tensor were to become a data representation rather than a model (#74), then free water DTI would be immediately supported. It would just be a mixture model with two components, one of which is a scalar and the other is a tensor.
