### ISSUE TITLE
OHBM action point 1: Pre-processed data

### ISSUE THREAD

**Issue by Lestropie** [bids-standard/bids-bep016#2]
Many of the JSON fields for pre-processed DWI data are in fact not specific to diffusion, and may be applicable to other types of pre-processed derivatives as well. As such, as many of these as is reasonable should be moved to "common derivatives".

Some other things I noticed more recently looking at the pre-processed data fields:

1. Gibbs ringing correction could have its own field.

2. `FieldInhomogeneityCorrection` could be changed from a Boolean to a string, in order to differentiate between "static" field correction (i.e. assuming an inhomogeneity field that remains constant despite subject rotations) and "dynamic" field correction (e.g. [manuscript](https://www.sciencedirect.com/science/article/pii/S1053811917310601); [`eddy` 6.0.1](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy).

3. Having "{ none, geometry, gradients, geometry&gradients }" as options for `GradientNonLinearityCorrection` feels clunky. It might make more sense to instead have two separate Booleans:

    1. Correction of geometric image distortions arising from gradient non-linearities;

    2. Correction of image intensities to match the global gradient table based on gradient non-linearities. Note however that this is not how such information is typically handled; it is more common to derive a gradient table per voxel based on the gradient non-linearity information during diffusion model fitting, which would not be applicable to "pre-processed DWI data" but to the model data.

**Comment by arokem** [comment]
Seems like this is not relevant to the current state of the BEP. Closing (but reopen if you think it still is).
