### ISSUE TITLE
OHBM Action Point 2: Separate tractography BEP

### ISSUE THREAD

**Issue by Lestropie** [bids-standard/bids-bep016#3]
Given the potential scope of the diffusion derivatives, and the lack of standardisation with respect to the storage of streamlines data, it was decided that it would be more pragmatic to remove all references to tractography from BEP016, and instead have a new standalone "Tractography derivatives", which would then be allowed to evolve over a a longer requisite time period. It would also give us the opportunity to afford the specification of diffusion models the amount of time and attention that they still require.

**Comment by oesteban** [comment]
I think we can keep BEP16, but using a different branch for tractography until models are merged into the main spec. Just to minimize the churn since we will be about the same people working on tractography.

**Comment by oesteban** [comment]
#9
