### ISSUE TITLE
Scope of BEP016

### ISSUE THREAD

**Issue by Lestropie** [bids-standard/bids-bep016#31]
"BEP016" is currently used to refer to "diffusion MRI derivatives" very generally.

What should be considered is whether BEP016 should instead refer solely to the incorporation of diffusion models, with downstream DWI derivatives being deferred to their own BEPs.

The advantage here is that the timeline for presentation of the diffusion model derivatives to both the wider community and to the BIDS spec maintainers will be much shorter. This means earlier feedback, and a greater likelihood of being used to set precedents that will be applicable to a very wide breadth of other derivative brain imaging data.

It would however make things slightly clunkier from the GitHub perspective as the repository is specifically named BEP016. Using separate repositories for separate DWI derivatives would not be as convenient; though you could nevertheless have e.g. tractography derivatives forking from the BEP016 repo (which is itself a fork), and regularly pulling in changes to diffusion models if they are relevant to derivation of the tractography derivatives.

**Comment by arokem** [comment]
+1 from me to the idea of starting with a BEP focused specifically on diffusion models and building on top of that for other downstream derivatives. I think that the benefits of this idea outweigh the potential GitHub clunkiness.
