### ISSUE TITLE
Tensor fitting software database

### ISSUE THREAD

**Issue by Lestropie** [bids-standard/bids-bep016#49]
As mentioned in #39, the introduction of new models into the specification should consider the breadth of softwares already available for fitting that model, as otherwise the specification may be too narrowly focused on the specifics of one particular implementation.

This however still applies to those models that survived #40.

I want to start by generating a list of softwares available for diffusion tensor fitting, even if only to consider the breadth of input parameters to put into the dictionary. But also things like inclusion of free water estimation could potentially also be incorporated, rather than being treated as a separate model. **Please do** contribute to this list if I miss any softwares or details of such.

-----

Other software compilations:

http://www.diffusion-imaging.com/2013/03/list-of-software-tools-for-dti.html

-----

#### ACID

http://diffusiontools.com/

Has basic linear tensor fitting with outlier detection

#### AFNI (FATCAT)

https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/tutorials/fatcat_prep/Postprocessing_I.html

Not a lot of detail, though there seems to be mention of parameter uncertainty.

#### BrainSuite

http://brainsuite.org/processing/diffusion/

Seemingly fixed weighted log-linear estimation.

#### Camino

http://camino.cs.ucl.ac.uk/index.php?n=Tutorials.DTI

Multiple weighting mechanisms for fitting, and RESTORE-based outlier rejection

#### DiPy

https://dipy.org/documentation/1.4.1./examples_built/reconst_dti/#example-reconst-dti

https://dipy.org/documentation/1.4.1./examples_built/restore_dti/#example-restore-dti

#### DoDTI

http://neuroimage.yonsei.ac.kr/dodti/

No particular details on tensor fitting

#### DSI Studio

http://dsi-studio.labsolver.org/Manual/Reconstruction#TOC-Diffusion-Tensor-Imaging-DTI-

Apparently same implementation as DTI Studio. But minimal info in the documentation.

#### DTI Studio

https://www.mristudio.org/user_manual/DTI%20Studio%20User_manual/tensor%20calculation.html

Looks like there may be different options for matrix solvers.

#### DTI-TK

http://dti-tk.sourceforge.net/pmwiki/pmwiki.php

Only checked the documentation briefly; looks like it operates on pre-computed tensors from other softwares?

#### ExploreDTI

http://exploredti.com/

No online documentation so don't know what options are available RE: tensor fitting.

#### FSL `dtifit`

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/UserGuide#DTIFIT

- Includes linear and weighted linear fits
- Also outputs model errors; we might want to consider standardisation of representation of model errors (irrespective of model)
- Can utilise gradient nonlinearity file

#### FreeSurfer

https://surfer.nmr.mgh.harvard.edu/fswiki/DiffusionTool

Have not used this myself; looks like it involves sampling tensor metrics, so it must be doing a tensor fit, but details are not documented online

#### *MRtrix3*

https://mrtrix.readthedocs.io/en/3.0.3/reference/commands/dwi2tensor.html

Ordinary least squares & iterative weighted least squares.

#### mrVista (mrDiffusion)

https://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/MrDiffusion

No details on fitting processes as far as I can see.

#### SPM

https://www.fil.ion.ucl.ac.uk/spm/ext/#Diffusion_II

Appears to be EOL?

#### TORTOISE

https://tortoise.nibib.nih.gov/tortoise/v313/12-step5-diffcalc-tensor-fitting-tortoise-version-313

Looks like a lot of different commands for tensor estimation; some are different weighted / linear / nonlinear fitting techniques, but I can't identify them all

#### TrackVis

http://www.trackvis.org/dtk/?subsect=script#dti_recon

- Capability to write tensor data as either 4D or 5D image; would be consequential for conversion functions

- Can include implicit masking via mean *b*=0

#### DTI BrainImageScope

http://www.columbia.edu/~dx2103/brainimagescope.html

Only dead links; likely no longer managed

#### Quest-NI

http://csci.ucsd.edu/quest-ni/index.html

Diffusion tensor imaging (DTI) for tissue microstructure assessment and the analysis of structural connectivity from tractography

#### TDF

https://resource.loni.usc.edu/resources/downloads/tensor-distribution-function-code/

Diffusion magnetic resonance imaging (dMRI) is a powerful tool for studying white matter microstructure features such as white matter connectivity and integrity in the human brain. Diffusion Tensor Imaging (DTI) has been the gold standard for measuring white matter microstructure, but DTI is not sufficient to resolve fiber crossings and intermixing of tracts. Since the tensor distribution function (TDF) represents the diffusion profile as a probabilistic mixture of tensors, it can be used to reconstruct multiple underlying fibers.

**Comment by francopestilli** [comment]
@Lestropie This is a great list.

I added another toolbox: http://csci.ucsd.edu/quest-ni/index.html

RE VISTASOFT, this is where some details of the fitting of the tensors are provided:
https://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/DTI_Preprocessing

**Comment by Lestropie** [comment]
VISTASOFT is I think the only one that has any mention of bootstrapping. But it doesn't actually yield bootstrap instances, it only provides:
- Standard deviation of FA
- Standard deviation of MD
- Variance in first eigenvector, calculated as the dispersion parameter of a Watson distribution

So these are all just scalar parametric maps; which are easy to represent, but we should nevertheless think about what the corresponding JSONs might look like. Might help in thinking about the general solution to this by decomposing into the constituent steps. E.g. Consider FA:
1.  Calculate max a posteriori tensor
    1. From this, calculate FA
1.  Calculate bootstrap realisations of tensor
    1. Calculate FA for each realisation
    1. Compute statistic (e.g. standard deviation; but could be anything else) across realisations
1. Delete bootstrap realisations of tensor from step 2 (as appears to be the case in VISTASOFT; but not always guaranteed to be the case)

So corresponding files might be something like (given proposal as it currently stands):
1.  `sub-##_desc-map_tensor.nii.gz` (XxYxZx6)
    1.  `sub-##_desc-map_fa.nii.gz` (XxYxZ)
1.  `sub-##_desc-bootstrap_tensor.nii.gz` (XxYxZx6xN)
    1.  `sub-##_desc-bootstrap_fa.nii.gz` (XxYxZxN)
    1.  `sub-##_desc-bootstrap_stat-std_fa.nii.gz` (XxYxZ)

So would be proposing new BIDS entity "stat" for calculation of statistics across a data dimension.

**Comment by francopestilli** [comment]
mmh. 'stat' would be a top-level BIDS term?
I worry that is a lot to ask, shall we try to finish this as is? Using 'desc'

**Comment by arokem** [comment]
+1. Let's punt on bootstrapping for now. I think that it could get complicated, and I have not seen any software that saves all of the boostrap samples.

**Comment by Lestropie** [comment]
> 'stat' would be a top-level BIDS term?
> I worry that is a lot to ask,  shall we try to finish this as is? Using 'desc'

That is the suggestion. It's an exceptionally general concept, and indeed one could argue that it would have reasonably been included in common derivatives. E.g. Calculating the mean across a time series or the like. The trouble with co-opting something like `desc` is that each entity can be used only once, and therefore if you have two separate dimensions requiring disambiguation (e.g. max a posteriori vs. bootstraps & different statistics across bootstraps) the utility breaks down.

I suspect that in time there will need to be a second entity table that applies only to derivatives, and that if we keep that in the back of our minds we'll start to see more and more instances of such.

> I have not seen any software that saves all of the bootstrap samples

For the tensor model, same; but given prevalence of `bedpostx` we'll need to sort out the concept eventually.

**Comment by francopestilli** [comment]
@Lestropie @arokem what do we have left here to resolve this issue? It sounds to me we are good except for `bebpostx`
Correct?

**Comment by Lestropie** [comment]
> What do we have left here to resolve this issue?

Things I want to think about (some of which may need to be branched to other Issue threads):

- Resolving "`FitMethod`" and "`Iterations`". I think that in the presence of the latter, "`iwls`" doesn't need to be an option for the former as contrasted against "`wls`".

- How to define weighted fitting. With the tensor model, weighting would be expected to be based on either the log of the signal, or the log of the predicted signal (the latter of which is preferable). For other models, different weighting schemes would certainly be possible. So this may require its own field.

- Appropriate naming convention for bootstrap-derived images (even if we don't need to immediately deal with the bootstraps themselves for the tensor model).

- What a general solution for describing outlier rejection in model fitting looks like. I don't think that having the presence / absence of RESTORE as a flag---or metadata fields named according to such---makes sense, given it's just one method.

**Comment by francopestilli** [comment]
- Resolving "FitMethod" and "Iterations". I think that in the presence of the latter, "iwls" doesn't need to be an option for the former as contrasted against "wls".

How to define weighted fitting. With the tensor model, weighting would be expected to be based on either the log of the signal, or the log of the predicted signal (the latter of which is preferable). For other models, different weighting schemes would certainly be possible. So this may require its own field.

Appropriate naming convention for bootstrap-derived images (even if we don't need to immediately deal with the bootstraps themselves for the tensor model).

What a general solution for describing outlier rejection in model fitting looks like. I don't think that having the presence / absence of RESTORE as a flag---or metadata fields named according to such---makes sense, given it's just one method.
