### ISSUE TITLE
Encoding of predicted b=0 image in eg. tensor fit

### ISSUE THREAD

**Issue by Lestropie** [bids-standard/bids-bep016#62]
Arguably the value for entity "`param-`" should be "`S0`" rather than "`bzero`".

**Comment by arokem** [comment]
Yes, agree completely. Is there anything counter-indicating the use of numbers in labels?

**Comment by Lestropie** [comment]
#92 removed entirely the notion of reserved "`param`" entity values; however in the demonstrative examples, "`_param-s0`" is used for the diffusion tensor estimated signal at *b*=0.
