### ISSUE TITLE
DiffusionScheme field

### ISSUE THREAD

**Issue by neurolabusc** [bids-standard/bids-bep016#86]
I would like to advocate that BIDS define the `DiffusionScheme` field from dcm2niix, with the possible values `Bipolar` and `Monopolar`. Philips and GE sequences typically use a monopolar [Stejskal-Tanner](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3003887/) sequence. Siemens user can often select between monopolar or bipolar [twice-refocused spin echo](https://pubmed.ncbi.nlm.nih.gov/12509835) sequences. Monopolar sequences enable a shorter echo time yielding better signal to noise, while bipolar sequences reduce spatial distortion in the raw data (though tools like eddy/TOPUP can attenuate this distortion).

**Comment by Lestropie** [comment]
I think this is outside the scope of BEP016. What I'm not sure about is whether it will be considered within scope of the main specification, or deferred to BEP033 ([docuument](https://docs.google.com/document/d/1en4ByORlPqwDfZwNOOBTj0GwpYBcS0_2peqreTOvwDU/edit#heading=h.4k1noo90gelw); [preprint](https://arxiv.org/abs/2103.14485); not sure that it was ever published fully).

Personally I would like to see it there as well as I already use it in my own processing: if data were acquired using monopolar, particularly if using a high b-value, then the interleaved *b*=0's can have residual eddy current distortions, and therefore shouldn't be used for susceptibility field estimation if the corresponding algorithm assumes only rigid body motion between volumes.

I would suggest posting on the main specification repo; please tag me there also so it comes up in my inbox.
